# Generated by Django 5.1.2 on 2026-02-03 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Brend nomi")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="brands/", verbose_name="Logo"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Kategoriya nomi"),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Rasm",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="I.B.T Watches",
                        max_length=100,
                        verbose_name="Sayt nomi",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(blank=True, verbose_name="Sayt tavsifi"),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+998909182842", max_length=20, verbose_name="Telefon"
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(
                        default="boburIBT",
                        max_length=100,
                        verbose_name="Telegram username",
                    ),
                ),
                (
                    "telegram_channel",
                    models.CharField(
                        default="IBTwatches",
                        max_length=100,
                        verbose_name="Telegram kanal",
                    ),
                ),
                (
                    "instagram_username",
                    models.CharField(
                        default="i.b.t_watches",
                        max_length=100,
                        verbose_name="Instagram",
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Bot Token"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=50, verbose_name="Chat ID"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Description"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Meta Keywords"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamalari",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Soat nomi")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="Slug"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Qisqa tavsif"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Narxi (so'm)"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Eski narxi",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Erkaklar"),
                            ("female", "Ayollar"),
                            ("unisex", "Unisex"),
                        ],
                        default="unisex",
                        max_length=10,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("like_new", "Yangiday"),
                            ("good", "Yaxshi"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="watches/", verbose_name="Asosiy rasm"),
                ),
                (
                    "is_new",
                    models.BooleanField(default=False, verbose_name="Yangi mahsulot"),
                ),
                (
                    "is_trending",
                    models.BooleanField(default=False, verbose_name="Trendda"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Tanlangan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="Sotuvda bor"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watches",
                        to="store.brand",
                        verbose_name="Brend",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watches",
                        to="store.category",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soat",
                "verbose_name_plural": "Soatlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Buyurtma raqami",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="To'liq ism"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Telefon raqam"),
                ),
                ("address", models.TextField(verbose_name="Manzil")),
                ("product_url", models.URLField(verbose_name="Mahsulot havolasi")),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Mahsulot narxi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("confirmed", "Tasdiqlangan"),
                            ("processing", "Jarayonda"),
                            ("shipped", "Jo'natildi"),
                            ("delivered", "Yetkazildi"),
                            ("completed", "Bajarildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "telegram_sent",
                    models.BooleanField(
                        default=False, verbose_name="Telegramga yuborildi"
                    ),
                ),
                (
                    "telegram_message_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telegram xabar ID"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin izohlari"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="store.watch",
                        verbose_name="Soat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="watches/gallery/", verbose_name="Rasm"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt text"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.watch",
                        verbose_name="Soat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soat rasmi",
                "verbose_name_plural": "Soat rasmlari",
                "ordering": ["order"],
            },
        ),
    ]
